server:
    port: 8081
# 多数据源路由配置
# mysql 5.x driver-class-name: com.mysql.jdbc.Driver    mysql-connector-java 5.1.34
# mysql 8.x driver-class-name: com.mysql.cj.jdbc.Driver mysql-connector-java 8.0.22
mini-db-router:
    jdbc:
        datasource:
            dbCount: 2
            tbCount: 4
            default: db00
            routerKey: uId
            list: db01,db02
            db00:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://192.168.137.100:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
                username: root
                password: admin
            db01:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://192.168.137.100:3306/test_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
                username: root
                password: admin
            db02:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://192.168.137.100:3306/test_02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
                username: root
                password: admin

# Mybatis
mybatis:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    config-location:  classpath:/mybatis/config/mybatis-config.xml

